# Generated by Django 5.1.4 on 2025-01-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_app', '0002_alter_carta_ataque_alter_carta_defensa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='atributo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carta',
            name='frame_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carta',
            name='raza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
