# Generated by Django 5.1.4 on 2025-01-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_app', '0003_carta_atributo_carta_frame_type_carta_raza'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartadeck',
            name='en_extra_deck',
            field=models.BooleanField(default=False),
        ),
    ]
